-- MySQL Script generated by MySQL Workbench
-- 04/15/16 15:00:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CivilCalc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CivilCalc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CivilCalc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CivilCalc` ;

-- -----------------------------------------------------
-- Table `CivilCalc`.`tipos_de_materiais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`tipos_de_materiais` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`tipos_de_materiais` (
  `id_tipo_material` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `codigo` VARCHAR(250) NULL,
  PRIMARY KEY (`id_tipo_material`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`unidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`unidades` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`unidades` (
  `id_unidade` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `simbolo` VARCHAR(20) NULL,
  PRIMARY KEY (`id_unidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`materiais_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`materiais_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`materiais_modelo` (
  `id_material_modelo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `descricao` VARCHAR(250) NULL,
  `fk_unidade` INT NULL,
  `fk_tipo` INT NULL,
  `valor_unitario` VARCHAR(45) NULL,
  `coeficiente` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `valor_por_fornecedor` ENUM('SIM', 'NAO') NULL,
  `valor_padrao_fornecedor` ENUM('MAIOR', 'MENOR', 'MEDIA', 'SELECIONAR') NULL,
  `tipo` ENUM('NORMAL', 'SINAPI') NULL,
  PRIMARY KEY (`id_material_modelo`),
  INDEX `fk_tipo_1_idx` (`fk_tipo` ASC),
  INDEX `fk_unidade_1_idx` (`fk_unidade` ASC),
  CONSTRAINT `fk_tipo_10`
    FOREIGN KEY (`fk_tipo`)
    REFERENCES `CivilCalc`.`tipos_de_materiais` (`id_tipo_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidade_10`
    FOREIGN KEY (`fk_unidade`)
    REFERENCES `CivilCalc`.`unidades` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`materiais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`materiais` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`materiais` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `descricao` VARCHAR(250) NULL,
  `fk_unidade` INT NULL,
  `fk_tipo` INT NULL,
  `valor_unitario` VARCHAR(45) NULL,
  `coeficiente` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `valor_por_fornecedor` ENUM('SIM', 'NAO') NULL,
  `valor_padrao_fornecedor` ENUM('MAIOR', 'MENOR', 'MEDIA', 'SELECIONAR') NULL,
  `fk_modelo` INT NULL,
  PRIMARY KEY (`id_material`),
  INDEX `fk_tipo_1_idx` (`fk_tipo` ASC),
  INDEX `fk_unidade_1_idx` (`fk_unidade` ASC),
  INDEX `fk_modelo_1_idx` (`fk_modelo` ASC),
  CONSTRAINT `fk_tipo_1`
    FOREIGN KEY (`fk_tipo`)
    REFERENCES `CivilCalc`.`tipos_de_materiais` (`id_tipo_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidade_1`
    FOREIGN KEY (`fk_unidade`)
    REFERENCES `CivilCalc`.`unidades` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo_1`
    FOREIGN KEY (`fk_modelo`)
    REFERENCES `CivilCalc`.`materiais_modelo` (`id_material_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(250) NULL,
  `num` VARCHAR(20) NULL,
  `cep` VARCHAR(15) NULL,
  `cidade` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `complemento` VARCHAR(250) NULL,
  `uf` VARCHAR(5) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`bdi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`bdi` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`bdi` (
  `id_bdi` INT NOT NULL AUTO_INCREMENT,
  `despesa_admin` VARCHAR(45) NULL,
  `iss` VARCHAR(45) NULL,
  `cofins` VARCHAR(45) NULL,
  `pis` VARCHAR(45) NULL,
  `cprb` VARCHAR(45) NULL,
  `custo_finan` VARCHAR(45) NULL,
  `risco_imprevisto` VARCHAR(45) NULL,
  `seguros` VARCHAR(45) NULL,
  `garantias` VARCHAR(45) NULL,
  `bonificacao` VARCHAR(45) NULL,
  `valor_final` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY (`id_bdi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`encargos_horistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`encargos_horistas` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`encargos_horistas` (
  `id_encargo_horista` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `inss_previdencia` VARCHAR(10) NULL,
  `fgts` VARCHAR(10) NULL,
  `salario_edu` VARCHAR(10) NULL,
  `sesi` VARCHAR(10) NULL,
  `senai` VARCHAR(10) NULL,
  `sebrae` VARCHAR(10) NULL,
  `incra` VARCHAR(10) NULL,
  `inss_seguro` VARCHAR(10) NULL,
  `seconci` VARCHAR(10) NULL,
  `repouso_semanal` VARCHAR(10) NULL,
  `aux_enfermidade` VARCHAR(10) NULL,
  `licen_paternidade` VARCHAR(10) NULL,
  `salario_13` VARCHAR(10) NULL,
  `imprevistos` VARCHAR(10) NULL,
  `sem_justa_causa` VARCHAR(10) NULL,
  `ferias` VARCHAR(10) NULL,
  `aviso_previo` VARCHAR(10) NULL,
  `reincidencia_a_b` VARCHAR(10) NULL,
  `vale_transporte` VARCHAR(10) NULL,
  `cafe_manha` VARCHAR(10) NULL,
  `refeicao` VARCHAR(10) NULL,
  `seguro_vida` VARCHAR(10) NULL,
  `eq_protecao_indiv` VARCHAR(10) NULL,
  `ferramentas_manu` VARCHAR(10) NULL,
  `valor_total` VARCHAR(10) NULL,
  `jornada_mensal` VARCHAR(10) NULL,
  `repouso_semanal_remu` VARCHAR(10) NULL,
  `feriados` VARCHAR(10) NULL,
  `aux_enfermidade_dias` VARCHAR(10) NULL,
  `licen_paternidade_dias` VARCHAR(10) NULL,
  `licen_maternidade_dias` VARCHAR(10) NULL,
  `faltas_justificadas` VARCHAR(10) NULL,
  `dias_chuva` VARCHAR(10) NULL,
  `aux_acidente` VARCHAR(10) NULL,
  `ferias_dias` VARCHAR(10) NULL,
  `ano_produtivo` VARCHAR(10) NULL,
  `ano_produtivo_sem_horas_trab` VARCHAR(10) NULL,
  `salario_13_dias` VARCHAR(10) NULL,
  `aviso_previo_indenizado` VARCHAR(10) NULL,
  `aviso_previo_trabalhado` VARCHAR(10) NULL,
  `ferias_indenizadas` VARCHAR(10) NULL,
  `despedida_injusta` VARCHAR(10) NULL,
  `indenizacao_adicional` VARCHAR(10) NULL,
  `custo_conducao` VARCHAR(10) NULL,
  `custo_cafe_manha` VARCHAR(10) NULL,
  `custo_refeicao` VARCHAR(10) NULL,
  `custo_seguro` VARCHAR(10) NULL,
  `custo_epi` VARCHAR(10) NULL,
  `salario_minimo` VARCHAR(10) NULL,
  `desligamentos` VARCHAR(10) NULL,
  `dispensa_injusta` VARCHAR(10) NULL,
  `dispensa_justa` VARCHAR(10) NULL,
  `espontaneos` VARCHAR(10) NULL,
  `fim_de_contrato_por_prazo` VARCHAR(10) NULL,
  `termino_de_contrato` VARCHAR(10) NULL,
  `aposentados` VARCHAR(10) NULL,
  `mortos` VARCHAR(10) NULL,
  `transferencias` VARCHAR(10) NULL,
  `estoque` VARCHAR(10) NULL,
  `estoque_recuperado_inicio` VARCHAR(10) NULL,
  `estoque_recuperado_fim` VARCHAR(10) NULL,
  `estoque_medio` VARCHAR(10) NULL,
  `dispensados_descontados` VARCHAR(10) NULL,
  `dispensados` VARCHAR(10) NULL,
  `rotatividade_descontada` VARCHAR(10) NULL,
  `rotatividade_nao_descontada` VARCHAR(10) NULL,
  `desligados_espontaneos` VARCHAR(10) NULL,
  `duracao_media_emprego` VARCHAR(10) NULL,
  `percentual_dispensa_injusta` VARCHAR(10) NULL,
  `num_refeicoes` INT NULL,
  `num_conducao` INT NULL,
  `num_ferramentas_manu` INT NULL,
  `val_a` VARCHAR(10) NULL,
  `val_b` VARCHAR(10) NULL,
  `val_c` VARCHAR(10) NULL,
  `val_d` VARCHAR(10) NULL,
  `val_e` VARCHAR(10) NULL,
  PRIMARY KEY (`id_encargo_horista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`encargos_mensalistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`encargos_mensalistas` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`encargos_mensalistas` (
  `id_encargo_mensalistas` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `inss_previdencia` VARCHAR(10) NULL,
  `fgts` VARCHAR(10) NULL,
  `salario_edu` VARCHAR(10) NULL,
  `sesi` VARCHAR(10) NULL,
  `senai` VARCHAR(10) NULL,
  `sebrae` VARCHAR(10) NULL,
  `incra` VARCHAR(10) NULL,
  `inss_seguro` VARCHAR(10) NULL,
  `seconci` VARCHAR(10) NULL,
  `salario` VARCHAR(10) NULL,
  `aux_enfermidade` VARCHAR(10) NULL,
  `reincidencia_a2_c3` VARCHAR(10) NULL,
  `imprevistos` VARCHAR(10) NULL,
  `sem_justa_causa` VARCHAR(10) NULL,
  `ferias` VARCHAR(10) NULL,
  `aviso_previo` VARCHAR(10) NULL,
  `reincidencia_a_b` VARCHAR(10) NULL,
  `vale_transporte` VARCHAR(10) NULL,
  `cafe_manha` VARCHAR(10) NULL,
  `refeicao` VARCHAR(10) NULL,
  `seguro_vida` VARCHAR(10) NULL,
  `eq_protecao_indiv` VARCHAR(10) NULL,
  `ferramentas_manu` VARCHAR(10) NULL,
  `valor_total` VARCHAR(10) NULL,
  `jornada_mensal` VARCHAR(10) NULL,
  `repouso_semanal_remu` VARCHAR(10) NULL,
  `feriados` VARCHAR(10) NULL,
  `aux_enfermidade_dias` VARCHAR(10) NULL,
  `licen_paternidade_dias` VARCHAR(10) NULL,
  `licen_maternidade_dias` VARCHAR(10) NULL,
  `faltas_justificadas` VARCHAR(10) NULL,
  `dias_chuva` VARCHAR(10) NULL,
  `aux_acidente` VARCHAR(10) NULL,
  `ferias_dias` VARCHAR(10) NULL,
  `ano_produtivo` VARCHAR(10) NULL,
  `ano_produtivo_sem_horas_trab` VARCHAR(10) NULL,
  `salario_13_dias` VARCHAR(10) NULL,
  `aviso_previo_indenizado` VARCHAR(10) NULL,
  `aviso_previo_trabalhado` VARCHAR(10) NULL,
  `ferias_indenizadas` VARCHAR(10) NULL,
  `despedida_injusta` VARCHAR(10) NULL,
  `indenizacao_adicional` VARCHAR(10) NULL,
  `custo_conducao` VARCHAR(10) NULL,
  `custo_cafe_manha` VARCHAR(10) NULL,
  `custo_refeicao` VARCHAR(10) NULL,
  `custo_seguro` VARCHAR(10) NULL,
  `custo_epi` VARCHAR(10) NULL,
  `salario_minimo` VARCHAR(10) NULL,
  `desligamentos` VARCHAR(10) NULL,
  `dispensa_injusta` VARCHAR(10) NULL,
  `dispensa_justa` VARCHAR(10) NULL,
  `espontaneos` VARCHAR(10) NULL,
  `fim_de_contrato_por_prazo` VARCHAR(10) NULL,
  `termino_de_contrato` VARCHAR(10) NULL,
  `aposentados` VARCHAR(10) NULL,
  `mortos` VARCHAR(10) NULL,
  `transferencias` VARCHAR(10) NULL,
  `estoque` VARCHAR(10) NULL,
  `estoque_recuperado_inicio` VARCHAR(10) NULL,
  `estoque_recuperado_fim` VARCHAR(10) NULL,
  `estoque_medio` VARCHAR(10) NULL,
  `dispensados_descontados` VARCHAR(10) NULL,
  `dispensados` VARCHAR(10) NULL,
  `rotatividade_descontada` VARCHAR(10) NULL,
  `rotatividade_nao_descontada` VARCHAR(10) NULL,
  `desligados_espontaneos` VARCHAR(10) NULL,
  `duracao_media_emprego` VARCHAR(10) NULL,
  `percentual_dispensa_injusta` VARCHAR(10) NULL,
  `num_refeicoes` INT NULL,
  `num_conducao` INT NULL,
  `num_ferramentas_manu` INT NULL,
  `val_a` VARCHAR(10) NULL,
  `val_b` VARCHAR(10) NULL,
  `val_c` VARCHAR(10) NULL,
  `val_d` VARCHAR(10) NULL,
  `val_e` VARCHAR(10) NULL,
  PRIMARY KEY (`id_encargo_mensalistas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`cargos` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`cargos` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`grupos_de_integrantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`grupos_de_integrantes` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`grupos_de_integrantes` (
  `id_grupo_de_integrante` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo_de_integrante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`integrantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`integrantes` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`integrantes` (
  `id_integrante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  `cpf_cnpj` VARCHAR(20) NULL,
  `tel` VARCHAR(20) NULL,
  `sexo` ENUM('MASC', 'FEM') NULL,
  `fk_cargo` INT NULL,
  `tipo` ENUM('PF','PJ') NULL,
  `fk_endereco` INT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `fk_grupo` INT NULL,
  `path_assinatura` VARCHAR(250) NULL,
  PRIMARY KEY (`id_integrante`),
  INDEX `fk_endereco_2_idx` (`fk_endereco` ASC),
  INDEX `fk_cargo_1_idx` (`fk_cargo` ASC),
  INDEX `fk_grupo_1_idx` (`fk_grupo` ASC),
  CONSTRAINT `fk_endereco_2`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `CivilCalc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargo_1`
    FOREIGN KEY (`fk_cargo`)
    REFERENCES `CivilCalc`.`cargos` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_1`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `CivilCalc`.`grupos_de_integrantes` (`id_grupo_de_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`projetos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`projetos` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`projetos` (
  `id_projeto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `objetivo` LONGTEXT NULL,
  `data_cadastro` DATE NULL,
  `obs` MEDIUMTEXT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `ordem` INT NULL,
  `path_logo` VARCHAR(250) NULL,
  `fk_endereco` INT NULL,
  `tomada_preco` VARCHAR(45) NULL,
  `fk_bdi` INT NULL,
  `fk_encargo_horista` INT NULL,
  `fk_encargo_mensalista` INT NULL,
  `id_referencia` VARCHAR(45) NULL,
  `fk_responsavel` INT NULL,
  PRIMARY KEY (`id_projeto`),
  INDEX `fk_endreco_5_idx` (`fk_endereco` ASC),
  INDEX `fk_bdi_idx` (`fk_bdi` ASC),
  INDEX `fk_encargo_horista_idx` (`fk_encargo_horista` ASC),
  INDEX `fk_encargo_mensalista_idx` (`fk_encargo_mensalista` ASC),
  INDEX `fk_responsavel_idx` (`fk_responsavel` ASC),
  CONSTRAINT `fk_endereco_5`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `CivilCalc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bdi`
    FOREIGN KEY (`fk_bdi`)
    REFERENCES `CivilCalc`.`bdi` (`id_bdi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encargo_horista`
    FOREIGN KEY (`fk_encargo_horista`)
    REFERENCES `CivilCalc`.`encargos_horistas` (`id_encargo_horista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encargo_mensalista`
    FOREIGN KEY (`fk_encargo_mensalista`)
    REFERENCES `CivilCalc`.`encargos_mensalistas` (`id_encargo_mensalistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsavel`
    FOREIGN KEY (`fk_responsavel`)
    REFERENCES `CivilCalc`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`projetos_x_integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`projetos_x_integrante` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`projetos_x_integrante` (
  `id_projetos_x_integrante` INT NOT NULL AUTO_INCREMENT,
  `fk_projeto` INT NULL,
  `fk_integrante` INT NULL,
  PRIMARY KEY (`id_projetos_x_integrante`),
  INDEX `fk_projeto_1_idx` (`fk_projeto` ASC),
  INDEX `fk_responsavel_1_idx` (`fk_integrante` ASC),
  CONSTRAINT `fk_projeto_1`
    FOREIGN KEY (`fk_projeto`)
    REFERENCES `CivilCalc`.`projetos` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_integrante`
    FOREIGN KEY (`fk_integrante`)
    REFERENCES `CivilCalc`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`proprietarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`proprietarios` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`proprietarios` (
  `id_proprietario` INT NOT NULL AUTO_INCREMENT,
  `nome_razao` VARCHAR(250) NULL,
  `cpf_cnpj` VARCHAR(20) NULL,
  `tipo` ENUM('PF','PJ') NULL,
  `tel_1` VARCHAR(20) NULL,
  `tel_2` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `fk_endereco` INT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY (`id_proprietario`),
  INDEX `fk_endereco_1_idx` (`fk_endereco` ASC),
  CONSTRAINT `fk_endereco_1`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `CivilCalc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`projetos_x_proprietarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`projetos_x_proprietarios` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`projetos_x_proprietarios` (
  `id_projetos_x_proprietarios` INT NOT NULL AUTO_INCREMENT,
  `fk_projeto` INT NULL,
  `fk_proprietario` INT NULL,
  PRIMARY KEY (`id_projetos_x_proprietarios`),
  INDEX `fk_projeto_1_idx` (`fk_projeto` ASC),
  INDEX `fk_proprietario_1_idx` (`fk_proprietario` ASC),
  CONSTRAINT `fk_projeto_3`
    FOREIGN KEY (`fk_projeto`)
    REFERENCES `CivilCalc`.`projetos` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proprietario_1`
    FOREIGN KEY (`fk_proprietario`)
    REFERENCES `CivilCalc`.`proprietarios` (`id_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`etapas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`etapas` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`etapas` (
  `id_etapa` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NULL,
  `fk_projeto` INT NULL,
  `objetivo` MEDIUMTEXT NULL,
  `obs` VARCHAR(250) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `ordem` INT NULL,
  PRIMARY KEY (`id_etapa`),
  INDEX `fk_projeto_3_idx` (`fk_projeto` ASC),
  CONSTRAINT `fk_projeto_4`
    FOREIGN KEY (`fk_projeto`)
    REFERENCES `CivilCalc`.`projetos` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`subetapas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`subetapas` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`subetapas` (
  `id_subetapa` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NULL,
  `fk_etapa` INT NULL,
  `objetivo` MEDIUMTEXT NULL,
  `obs` VARCHAR(250) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `ordem` INT NULL,
  PRIMARY KEY (`id_subetapa`),
  INDEX `fk_etapa_1_idx` (`fk_etapa` ASC),
  CONSTRAINT `fk_etapa_1`
    FOREIGN KEY (`fk_etapa`)
    REFERENCES `CivilCalc`.`etapas` (`id_etapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`itens_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`itens_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`itens_modelo` (
  `id_item_modelo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(250) NULL,
  `descricao` VARCHAR(250) NULL,
  `valor_unitario` VARCHAR(45) NULL,
  `fk_unidade` INT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `sem_insumos` ENUM('SIM', 'NAO') NULL,
  `tipo` ENUM('NORMAL', 'SINAPI') NULL,
  PRIMARY KEY (`id_item_modelo`),
  INDEX `fk_unidade_2_idx` (`fk_unidade` ASC),
  CONSTRAINT `fk_unidade_2`
    FOREIGN KEY (`fk_unidade`)
    REFERENCES `CivilCalc`.`unidades` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`item_modelo_x_material_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`item_modelo_x_material_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`item_modelo_x_material_modelo` (
  `id_item_x_material_modelo` INT NOT NULL AUTO_INCREMENT,
  `fk_item` INT NULL,
  `fk_material` INT NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item_x_material_modelo`),
  INDEX `fk_item_2_idx` (`fk_item` ASC),
  INDEX `fk_material_modelo_idx` (`fk_material` ASC),
  CONSTRAINT `fk_item_modelo`
    FOREIGN KEY (`fk_item`)
    REFERENCES `CivilCalc`.`itens_modelo` (`id_item_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_modelo`
    FOREIGN KEY (`fk_material`)
    REFERENCES `CivilCalc`.`materiais_modelo` (`id_material_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`equipamentos_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`equipamentos_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`equipamentos_modelo` (
  `id_equipamento_modelo` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `descricao` VARCHAR(250) NULL,
  `fk_unidade` INT NULL,
  `valor_unitario` VARCHAR(45) NULL,
  `tipo` ENUM('OPERATRIZ', 'TRANSPORTE', 'OUTROS') NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_equipamento_modelo`),
  INDEX `fk_unidade_3_idx` (`fk_unidade` ASC),
  CONSTRAINT `fk_unidade_30`
    FOREIGN KEY (`fk_unidade`)
    REFERENCES `CivilCalc`.`unidades` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`equipamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`equipamentos` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`equipamentos` (
  `id_equipamento` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `descricao` VARCHAR(250) NULL,
  `fk_unidade` INT NULL,
  `tipo` ENUM('OPERATRIZ', 'TRANSPORTE', 'OUTROS') NULL,
  `codigo` VARCHAR(45) NULL,
  `fk_modelo` INT NULL,
  `valor_unitario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_equipamento`),
  INDEX `fk_unidade_3_idx` (`fk_unidade` ASC),
  INDEX `fk_modelo_2_idx` (`fk_modelo` ASC),
  CONSTRAINT `fk_unidade_3`
    FOREIGN KEY (`fk_unidade`)
    REFERENCES `CivilCalc`.`unidades` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo_2`
    FOREIGN KEY (`fk_modelo`)
    REFERENCES `CivilCalc`.`equipamentos_modelo` (`id_equipamento_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`item_modelo_x_equipamento_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`item_modelo_x_equipamento_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`item_modelo_x_equipamento_modelo` (
  `id_item_x_equipamento_modelo` INT NOT NULL AUTO_INCREMENT,
  `fk_item` INT NULL,
  `fk_equipamento` INT NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item_x_equipamento_modelo`),
  INDEX `fk_item_modelo_2_idx` (`fk_item` ASC),
  INDEX `fk_equipamento_modelo_idx` (`fk_equipamento` ASC),
  CONSTRAINT `fk_item_modelo_2`
    FOREIGN KEY (`fk_item`)
    REFERENCES `CivilCalc`.`itens_modelo` (`id_item_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipamento_modelo`
    FOREIGN KEY (`fk_equipamento`)
    REFERENCES `CivilCalc`.`equipamentos_modelo` (`id_equipamento_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`tipos_mao_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`tipos_mao_obra` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`tipos_mao_obra` (
  `id_tipo_mao_obra` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `codigo` VARCHAR(250) NULL,
  PRIMARY KEY (`id_tipo_mao_obra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`mao_de_obra_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`mao_de_obra_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`mao_de_obra_modelo` (
  `id_mao_de_obra_modelo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `fk_tipo` INT NULL,
  `valor_unitario` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `codigo` VARCHAR(45) NULL,
  `fk_unidade` INT NULL,
  `ls_tipo` ENUM('HORISTA', 'MENSALISTA') NULL,
  PRIMARY KEY (`id_mao_de_obra_modelo`),
  INDEX `fk_tipo_2_idx` (`fk_tipo` ASC),
  INDEX `fk_unidade_idx` (`fk_unidade` ASC),
  CONSTRAINT `fk_tipo_20`
    FOREIGN KEY (`fk_tipo`)
    REFERENCES `CivilCalc`.`tipos_mao_obra` (`id_tipo_mao_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidade_7`
    FOREIGN KEY (`fk_unidade`)
    REFERENCES `CivilCalc`.`unidades` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`mao_de_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`mao_de_obra` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`mao_de_obra` (
  `id_mao_de_obra` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `fk_tipo` INT NULL,
  `valor_unitario` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `codigo` VARCHAR(45) NULL,
  `fk_unidade` INT NULL,
  `fk_modelo` INT NULL,
  `ls_tipo` ENUM('HORISTA', 'MENSALISTA') NULL,
  PRIMARY KEY (`id_mao_de_obra`),
  INDEX `fk_tipo_2_idx` (`fk_tipo` ASC),
  INDEX `fk_unidade__idx` (`fk_unidade` ASC),
  INDEX `fk_modelo_3_idx` (`fk_modelo` ASC),
  CONSTRAINT `fk_tipo_2`
    FOREIGN KEY (`fk_tipo`)
    REFERENCES `CivilCalc`.`tipos_mao_obra` (`id_tipo_mao_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidade_11`
    FOREIGN KEY (`fk_unidade`)
    REFERENCES `CivilCalc`.`unidades` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo_3`
    FOREIGN KEY (`fk_modelo`)
    REFERENCES `CivilCalc`.`mao_de_obra_modelo` (`id_mao_de_obra_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`item_modelo_x_mao_obra_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`item_modelo_x_mao_obra_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`item_modelo_x_mao_obra_modelo` (
  `id_item_x_mao_obra_modelo` INT NOT NULL AUTO_INCREMENT,
  `fk_item` INT NULL,
  `fk_mao_obra` INT NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item_x_mao_obra_modelo`),
  INDEX `fk_item_modelo_3_idx` (`fk_item` ASC),
  INDEX `fk_mao_obra_modelo_idx` (`fk_mao_obra` ASC),
  CONSTRAINT `fk_item_modelo_3`
    FOREIGN KEY (`fk_item`)
    REFERENCES `CivilCalc`.`itens_modelo` (`id_item_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mao_obra_modelo`
    FOREIGN KEY (`fk_mao_obra`)
    REFERENCES `CivilCalc`.`mao_de_obra_modelo` (`id_mao_de_obra_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`itens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`itens` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`itens` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(250) NULL,
  `descricao` VARCHAR(250) NULL,
  `valor_unitario` VARCHAR(45) NULL,
  `fk_unidade` INT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `fk_subetapa` INT NULL,
  `quantidade` VARCHAR(45) NULL,
  `fk_modelo` INT NULL,
  `valor_total` VARCHAR(45) NULL,
  `sem_insumos` ENUM('SIM', 'NAO') NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_unidade_2_idx` (`fk_unidade` ASC),
  INDEX `fk_subetapa_idx` (`fk_subetapa` ASC),
  INDEX `fk_modelo_idx` (`fk_modelo` ASC),
  CONSTRAINT `fk_unidade_6`
    FOREIGN KEY (`fk_unidade`)
    REFERENCES `CivilCalc`.`unidades` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subetapa`
    FOREIGN KEY (`fk_subetapa`)
    REFERENCES `CivilCalc`.`subetapas` (`id_subetapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo`
    FOREIGN KEY (`fk_modelo`)
    REFERENCES `CivilCalc`.`itens_modelo` (`id_item_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`item_x_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`item_x_material` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`item_x_material` (
  `id_item_x_material` INT NOT NULL AUTO_INCREMENT,
  `fk_item` INT NULL,
  `fk_material` INT NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item_x_material`),
  INDEX `fk_item_2_idx` (`fk_item` ASC),
  INDEX `fk_material_2_idx` (`fk_material` ASC),
  CONSTRAINT `fk_item_2`
    FOREIGN KEY (`fk_item`)
    REFERENCES `CivilCalc`.`itens` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material`
    FOREIGN KEY (`fk_material`)
    REFERENCES `CivilCalc`.`materiais` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`item_x_equipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`item_x_equipamento` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`item_x_equipamento` (
  `id_item_x_equipamento` INT NOT NULL AUTO_INCREMENT,
  `fk_item` INT NULL,
  `fk_equipamento` INT NULL,
  `quantidade` VARCHAR(45) NULL,
  `valor_unitario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item_x_equipamento`),
  INDEX `fk_equipamento_modelo_idx` (`fk_equipamento` ASC),
  INDEX `fk_item_modelo_2_idx` (`fk_item` ASC),
  CONSTRAINT `fk_item_3`
    FOREIGN KEY (`fk_item`)
    REFERENCES `CivilCalc`.`itens` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipamento`
    FOREIGN KEY (`fk_equipamento`)
    REFERENCES `CivilCalc`.`equipamentos` (`id_equipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`item_x_mao_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`item_x_mao_obra` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`item_x_mao_obra` (
  `id_item_x_mao_obra` INT NOT NULL AUTO_INCREMENT,
  `fk_item` INT NULL,
  `fk_mao_obra` INT NULL,
  `quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item_x_mao_obra`),
  INDEX `fk_item_modelo_3_idx` (`fk_item` ASC),
  INDEX `fk_mao_obra_modelo_idx` (`fk_mao_obra` ASC),
  CONSTRAINT `fk_item_4`
    FOREIGN KEY (`fk_item`)
    REFERENCES `CivilCalc`.`itens` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mao_obra`
    FOREIGN KEY (`fk_mao_obra`)
    REFERENCES `CivilCalc`.`mao_de_obra` (`id_mao_de_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`fornecedores` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`fornecedores` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome_razao` VARCHAR(250) NULL,
  `fk_endereco` INT NULL,
  `tipo` ENUM('PF', 'PJ') NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `nome_fantasia` VARCHAR(250) NULL,
  `tel_1` VARCHAR(45) NULL,
  `tel_2` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `nome_responsavel` VARCHAR(250) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `rg_ie` VARCHAR(45) NULL,
  `data_cadastro` DATE NULL,
  PRIMARY KEY (`id_fornecedor`),
  INDEX `fk_endereco_3_idx` (`fk_endereco` ASC),
  CONSTRAINT `fk_endereco_3`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `CivilCalc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`material_modelo_x_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`material_modelo_x_fornecedor` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`material_modelo_x_fornecedor` (
  `id_material_modelo_x_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `fk_material` INT NULL,
  `fk_fornecedor` INT NULL,
  `preco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_material_modelo_x_fornecedor`),
  INDEX `fk_fornecedor_1_idx` (`fk_fornecedor` ASC),
  INDEX `fk_material_modelo_2_idx` (`fk_material` ASC),
  CONSTRAINT `fk_material_modelo_2`
    FOREIGN KEY (`fk_material`)
    REFERENCES `CivilCalc`.`materiais_modelo` (`id_material_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_10`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `CivilCalc`.`fornecedores` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`dados_encargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`dados_encargos` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`dados_encargos` (
  `id_dados_encargo` INT NOT NULL AUTO_INCREMENT,
  `jornada_mensal` VARCHAR(10) NULL,
  `repouso_semanal_remu` VARCHAR(10) NULL,
  `feriados` VARCHAR(10) NULL,
  `aux_enfermidade` VARCHAR(10) NULL,
  `licen_paternidade` VARCHAR(10) NULL,
  `licen_maternidade` VARCHAR(10) NULL,
  `faltas_justificadas` VARCHAR(10) NULL,
  `dias_chuva` VARCHAR(10) NULL,
  `aux_acidente` VARCHAR(10) NULL,
  `ferias` VARCHAR(10) NULL,
  `ano_produtivo` VARCHAR(10) NULL,
  `ano_produtivo_sem_horas_trab` VARCHAR(10) NULL,
  `salario_13` VARCHAR(10) NULL,
  `aviso_previo_indenizado` VARCHAR(10) NULL,
  `aviso_previo_trabalhado` VARCHAR(10) NULL,
  `ferias_indenizadas` VARCHAR(10) NULL,
  `despedida_injusta` VARCHAR(10) NULL,
  `indenizacao_adicional` VARCHAR(10) NULL,
  `custo_conducao` VARCHAR(10) NULL,
  `custo_cafe_manha` VARCHAR(10) NULL,
  `custo_refeicao` VARCHAR(10) NULL,
  `custo_seguro` VARCHAR(10) NULL,
  `custo_epi` VARCHAR(10) NULL,
  `salario_minimo` VARCHAR(10) NULL,
  `desligamentos` VARCHAR(10) NULL,
  `dispensa_injusta` VARCHAR(10) NULL,
  `dispensa_justa` VARCHAR(10) NULL,
  `espontaneos` VARCHAR(10) NULL,
  `fim_de_contrato_por_prazo` VARCHAR(10) NULL,
  `termino_de_contrato` VARCHAR(10) NULL,
  `aposentados` VARCHAR(10) NULL,
  `mortos` VARCHAR(10) NULL,
  `transferencias` VARCHAR(10) NULL,
  `estoque` VARCHAR(10) NULL,
  `estoque_recuperado_inicio` VARCHAR(10) NULL,
  `estoque_recuperado_fim` VARCHAR(10) NULL,
  `estoque_medio` VARCHAR(10) NULL,
  `dispensados_descontados` VARCHAR(10) NULL,
  `dispensados` VARCHAR(10) NULL,
  `rotatividade_descontada` VARCHAR(10) NULL,
  `rotatividade_nao_descontada` VARCHAR(10) NULL,
  `desligados_espontaneos` VARCHAR(10) NULL,
  `duracao_media_emprego` VARCHAR(10) NULL,
  `percentual_dispensa_injusta` VARCHAR(10) NULL,
  `num_refeicoes` INT NULL,
  `num_conducao` INT NULL,
  `num_ferramentas_manu` INT NULL,
  PRIMARY KEY (`id_dados_encargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`empresa` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome_razao` VARCHAR(250) NULL,
  `nome_fantasia` VARCHAR(250) NULL,
  `lema` VARCHAR(250) NULL,
  `fk_endereco` INT NULL,
  `tel_1` VARCHAR(45) NULL,
  `tel_2` VARCHAR(45) NULL,
  `site` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `codigo` VARCHAR(45) NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `insc_municipal` VARCHAR(45) NULL,
  `insc_estadual` VARCHAR(45) NULL,
  `fk_dados_encargo` INT NULL,
  `acesso_rapido` VARCHAR(250) NULL,
  PRIMARY KEY (`id_empresa`),
  INDEX `fk_endereco_4_idx` (`fk_endereco` ASC),
  INDEX `fk_dados_encargo_idx` (`fk_dados_encargo` ASC),
  CONSTRAINT `fk_endereco_4`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `CivilCalc`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dados_encargo`
    FOREIGN KEY (`fk_dados_encargo`)
    REFERENCES `CivilCalc`.`dados_encargos` (`id_dados_encargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`cronograma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`cronograma` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`cronograma` (
  `id_cronograma` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('ETAPA','SUBETAPA') NULL,
  `fk_etapa` INT NULL,
  `fk_subetapa` INT NULL,
  `duracao_meses` INT NULL,
  `valor_total` VARCHAR(45) NULL,
  `fk_projeto` INT NULL,
  PRIMARY KEY (`id_cronograma`),
  INDEX `fk_etapa_2_idx` (`fk_etapa` ASC),
  INDEX `fk_subetapa_2_idx` (`fk_subetapa` ASC),
  INDEX `fk_projeto_5_idx` (`fk_projeto` ASC),
  CONSTRAINT `fk_etapa_2`
    FOREIGN KEY (`fk_etapa`)
    REFERENCES `CivilCalc`.`etapas` (`id_etapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subetapa_2`
    FOREIGN KEY (`fk_subetapa`)
    REFERENCES `CivilCalc`.`subetapas` (`id_subetapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_5`
    FOREIGN KEY (`fk_projeto`)
    REFERENCES `CivilCalc`.`projetos` (`id_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`itens_de_cronograma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`itens_de_cronograma` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`itens_de_cronograma` (
  `id_item_de_cronograma` INT NOT NULL AUTO_INCREMENT,
  `mes` INT NULL,
  `valor` VARCHAR(45) NULL,
  `fk_cronograma` INT NULL,
  `itens_de_cronogramacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item_de_cronograma`),
  INDEX `fk_cronograma_idx` (`fk_cronograma` ASC),
  CONSTRAINT `fk_cronograma`
    FOREIGN KEY (`fk_cronograma`)
    REFERENCES `CivilCalc`.`cronograma` (`id_cronograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`encargos_horistas_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`encargos_horistas_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`encargos_horistas_modelo` (
  `id_encargo_horista_modelo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `inss_previdencia` VARCHAR(10) NULL,
  `fgts` VARCHAR(10) NULL,
  `salario_edu` VARCHAR(10) NULL,
  `sesi` VARCHAR(10) NULL,
  `senai` VARCHAR(10) NULL,
  `sebrae` VARCHAR(10) NULL,
  `incra` VARCHAR(10) NULL,
  `inss_seguro` VARCHAR(10) NULL,
  `seconci` VARCHAR(10) NULL,
  `repouso_semanal` VARCHAR(10) NULL,
  `aux_enfermidade` VARCHAR(10) NULL,
  `licen_paternidade` VARCHAR(10) NULL,
  `salario_13` VARCHAR(10) NULL,
  `imprevistos` VARCHAR(10) NULL,
  `sem_justa_causa` VARCHAR(10) NULL,
  `ferias` VARCHAR(10) NULL,
  `aviso_previo` VARCHAR(10) NULL,
  `reincidencia_a_b` VARCHAR(10) NULL,
  `vale_transporte` VARCHAR(10) NULL,
  `cafe_manha` VARCHAR(10) NULL,
  `refeicao` VARCHAR(10) NULL,
  `seguro_vida` VARCHAR(10) NULL,
  `eq_protecao_indiv` VARCHAR(10) NULL,
  `ferramentas_manu` VARCHAR(10) NULL,
  `valor_total` VARCHAR(10) NULL,
  `jornada_mensal` VARCHAR(10) NULL,
  `repouso_semanal_remu` VARCHAR(10) NULL,
  `feriados` VARCHAR(10) NULL,
  `aux_enfermidade_dias` VARCHAR(10) NULL,
  `licen_paternidade_dias` VARCHAR(10) NULL,
  `licen_maternidade_dias` VARCHAR(10) NULL,
  `faltas_justificadas` VARCHAR(10) NULL,
  `dias_chuva` VARCHAR(10) NULL,
  `aux_acidente` VARCHAR(10) NULL,
  `ferias_dias` VARCHAR(10) NULL,
  `ano_produtivo` VARCHAR(10) NULL,
  `ano_produtivo_sem_horas_trab` VARCHAR(10) NULL,
  `salario_13_dias` VARCHAR(10) NULL,
  `aviso_previo_indenizado` VARCHAR(10) NULL,
  `aviso_previo_trabalhado` VARCHAR(10) NULL,
  `ferias_indenizadas` VARCHAR(10) NULL,
  `despedida_injusta` VARCHAR(10) NULL,
  `indenizacao_adicional` VARCHAR(10) NULL,
  `custo_conducao` VARCHAR(10) NULL,
  `custo_cafe_manha` VARCHAR(10) NULL,
  `custo_refeicao` VARCHAR(10) NULL,
  `custo_seguro` VARCHAR(10) NULL,
  `custo_epi` VARCHAR(10) NULL,
  `salario_minimo` VARCHAR(10) NULL,
  `desligamentos` VARCHAR(10) NULL,
  `dispensa_injusta` VARCHAR(10) NULL,
  `dispensa_justa` VARCHAR(10) NULL,
  `espontaneos` VARCHAR(10) NULL,
  `fim_de_contrato_por_prazo` VARCHAR(10) NULL,
  `termino_de_contrato` VARCHAR(10) NULL,
  `aposentados` VARCHAR(10) NULL,
  `mortos` VARCHAR(10) NULL,
  `transferencias` VARCHAR(10) NULL,
  `estoque` VARCHAR(10) NULL,
  `estoque_recuperado_inicio` VARCHAR(10) NULL,
  `estoque_recuperado_fim` VARCHAR(10) NULL,
  `estoque_medio` VARCHAR(10) NULL,
  `dispensados_descontados` VARCHAR(10) NULL,
  `dispensados` VARCHAR(10) NULL,
  `rotatividade_descontada` VARCHAR(10) NULL,
  `rotatividade_nao_descontada` VARCHAR(10) NULL,
  `desligados_espontaneos` VARCHAR(10) NULL,
  `duracao_media_emprego` VARCHAR(10) NULL,
  `percentual_dispensa_injusta` VARCHAR(10) NULL,
  `num_refeicoes` INT NULL,
  `num_conducao` INT NULL,
  `num_ferramentas_manu` INT NULL,
  `val_a` VARCHAR(10) NULL,
  `val_b` VARCHAR(10) NULL,
  `val_c` VARCHAR(10) NULL,
  `val_d` VARCHAR(10) NULL,
  `val_e` VARCHAR(10) NULL,
  PRIMARY KEY (`id_encargo_horista_modelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`encargos_mensalistas_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`encargos_mensalistas_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`encargos_mensalistas_modelo` (
  `id_encargo_mensalistas_modelo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  `inss_previdencia` VARCHAR(10) NULL,
  `fgts` VARCHAR(10) NULL,
  `salario_edu` VARCHAR(10) NULL,
  `sesi` VARCHAR(10) NULL,
  `senai` VARCHAR(10) NULL,
  `sebrae` VARCHAR(10) NULL,
  `incra` VARCHAR(10) NULL,
  `inss_seguro` VARCHAR(10) NULL,
  `seconci` VARCHAR(10) NULL,
  `salario` VARCHAR(10) NULL,
  `sem_justa_causa` VARCHAR(10) NULL,
  `imprevistos` VARCHAR(10) NULL,
  `ferias` VARCHAR(10) NULL,
  `aviso_previo` VARCHAR(10) NULL,
  `reincidencia_a_b` VARCHAR(10) NULL,
  `reincidencia_a2_c3` VARCHAR(10) NULL,
  `vale_transporte` VARCHAR(45) NULL,
  `cafe_manha` VARCHAR(10) NULL,
  `refeicao` VARCHAR(10) NULL,
  `seguro_vida` VARCHAR(10) NULL,
  `eq_protecao_indiv` VARCHAR(10) NULL,
  `ferramentas_manu` VARCHAR(10) NULL,
  `valor_total` VARCHAR(10) NULL,
  `jornada_mensal` VARCHAR(10) NULL,
  `repouso_semanal_remu` VARCHAR(10) NULL,
  `feriados` VARCHAR(10) NULL,
  `aux_enfermidade_dias` VARCHAR(10) NULL,
  `licen_paternidade_dias` VARCHAR(10) NULL,
  `licen_maternidade_dias` VARCHAR(10) NULL,
  `faltas_justificadas` VARCHAR(10) NULL,
  `dias_chuva` VARCHAR(10) NULL,
  `aux_acidente` VARCHAR(10) NULL,
  `ferias_dias` VARCHAR(10) NULL,
  `ano_produtivo` VARCHAR(10) NULL,
  `ano_produtivo_sem_horas_trab` VARCHAR(10) NULL,
  `salario_13_dias` VARCHAR(10) NULL,
  `aviso_previo_indenizado` VARCHAR(10) NULL,
  `aviso_previo_trabalhado` VARCHAR(10) NULL,
  `ferias_indenizadas` VARCHAR(10) NULL,
  `despedida_injusta` VARCHAR(10) NULL,
  `indenizacao_adicional` VARCHAR(10) NULL,
  `custo_conducao` VARCHAR(10) NULL,
  `custo_cafe_manha` VARCHAR(10) NULL,
  `custo_refeicao` VARCHAR(10) NULL,
  `custo_seguro` VARCHAR(10) NULL,
  `custo_epi` VARCHAR(10) NULL,
  `salario_minimo` VARCHAR(10) NULL,
  `desligamentos` VARCHAR(10) NULL,
  `dispensa_injusta` VARCHAR(10) NULL,
  `dispensa_justa` VARCHAR(10) NULL,
  `espontaneos` VARCHAR(10) NULL,
  `fim_de_contrato_por_prazo` VARCHAR(10) NULL,
  `termino_de_contrato` VARCHAR(10) NULL,
  `aposentados` VARCHAR(10) NULL,
  `mortos` VARCHAR(10) NULL,
  `transferencias` VARCHAR(10) NULL,
  `estoque` VARCHAR(10) NULL,
  `estoque_recuperado_inicio` VARCHAR(10) NULL,
  `estoque_recuperado_fim` VARCHAR(10) NULL,
  `estoque_medio` VARCHAR(10) NULL,
  `dispensados_descontados` VARCHAR(10) NULL,
  `dispensados` VARCHAR(10) NULL,
  `rotatividade_descontada` VARCHAR(10) NULL,
  `rotatividade_nao_descontada` VARCHAR(10) NULL,
  `desligados_espontaneos` VARCHAR(10) NULL,
  `duracao_media_emprego` VARCHAR(10) NULL,
  `percentual_dispensa_injusta` VARCHAR(10) NULL,
  `num_refeicoes` INT NULL,
  `num_conducao` INT NULL,
  `num_ferramentas_manu` INT NULL,
  `val_a` VARCHAR(10) NULL,
  `val_b` VARCHAR(10) NULL,
  `val_c` VARCHAR(10) NULL,
  `val_d` VARCHAR(10) NULL,
  `val_e` VARCHAR(10) NULL,
  PRIMARY KEY (`id_encargo_mensalistas_modelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`bdi_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`bdi_modelo` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`bdi_modelo` (
  `id_bdi_modelo` INT NOT NULL AUTO_INCREMENT,
  `despesa_admin` VARCHAR(45) NULL,
  `iss` VARCHAR(45) NULL,
  `cofins` VARCHAR(45) NULL,
  `pis` VARCHAR(45) NULL,
  `cprb` VARCHAR(45) NULL,
  `custo_finan` VARCHAR(45) NULL,
  `risco_imprevisto` VARCHAR(45) NULL,
  `seguros` VARCHAR(45) NULL,
  `garantias` VARCHAR(45) NULL,
  `bonificacao` VARCHAR(45) NULL,
  `valor_final` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY (`id_bdi_modelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CivilCalc`.`material_x_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CivilCalc`.`material_x_fornecedor` ;

CREATE TABLE IF NOT EXISTS `CivilCalc`.`material_x_fornecedor` (
  `id_material_x_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `fk_material` INT NULL,
  `fk_fornecedor` INT NULL,
  `preco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_material_x_fornecedor`),
  INDEX `fk_fornecedor_2_idx` (`fk_fornecedor` ASC),
  INDEX `fk_material_2_idx` (`fk_material` ASC),
  CONSTRAINT `fk_material_3`
    FOREIGN KEY (`fk_material`)
    REFERENCES `CivilCalc`.`materiais` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_2`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `CivilCalc`.`fornecedores` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
